# JWT 토큰을 만들려면 이슈 발급자(issuer), 비밀키(secret_key)를 필수적으로 설정
jwt:
  issuer: seungchan141414@gmail.com
  secret_key: nct-springboot

springdoc:
  packages-to-scan: back.springbootdeveloper.seungchan.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha